name: Create and Push Multi-Arch Ansible Execution Environment Image

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      registry:
        description: 'Container registry'
        required: false
        default: 'docker-sandbox.infra.cloudera.com'
      image_name:
        description: 'Image name'
        required: false
        default: 'goes/<YOUR_REPO_NAME>'
      tag_override:
        description: 'Override tag (optional - uses hatch version if empty)'
        required: false
        default: ''
      build_directory:
        description: 'Directory containing execution-environment.yml (leave as "." for root directory)'
        required: false
        default: 'instructor/public-cloud'
      push_latest:
        description: 'Also tag and push as latest'
        required: false
        type: boolean
        default: false

env:
  REGISTRY: ${{ github.event.inputs.registry || 'docker-sandbox.infra.cloudera.com' }}
  IMAGE_NAME: ${{ github.event.inputs.image_name || 'goes/<YOUR_REPO_NAME>' }}
  BUILD_DIR: ${{ github.event.inputs.build_directory || 'instructor/public-cloud' }}
  PUSH_LATEST: ${{ github.event.inputs.push_latest || true }}
  TAG_OVERRIDE: ${{ github.event.inputs.tag_override || '' }}

jobs:
  multi-arch-ee:
    if: github.repository == 'goes/<YOUR_REPO_NAME>'

    runs-on: multi-arch-ee

    steps:

    - name: Clean up working directory
      run: |
        # The workspace is the directory where the repository is checked out.
        # We use `sudo` because some files might be owned by root from a previous
        # build (e.g., from a failed `ansible-builder` command).
        rm -rf ${{ github.workspace }}/*

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build and Push Multi-Arch Image
      uses: goes/github-actions/actions/multi-ee-action@main
      with:
        registry: ${{ env.REGISTRY }}
        image_name: ${{ env.IMAGE_NAME }}
        tag_override: ${{ env.TAG_OVERRIDE }}
        build_directory: ${{ env.BUILD_DIR }}
        push_latest: ${{ env.PUSH_LATEST }}
        registry_user: ${{ secrets.REGISTRY_USER }}
        registry_password: ${{ secrets.REGISTRY_PASSWORD }}
